<<<<<<< HEAD
# Generated by Django 4.2 on 2026-05-23 19:12

=======
# Generated by Django 6.0.5 on 2026-06-02 06:58

import django.db.models.deletion
>>>>>>> 940edef (Lab 6 completado)
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
=======
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('birth_date', models.DateField()),
                ('level', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('P', 'Planta'), ('T', 'Tierra'), ('L', 'Lagartija'), ('A', 'Agua'), ('E', 'Eléctrico'), ('F', 'Fuego')], max_length=50)),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('picture', models.ImageField(upload_to='pokemon_images')),
                ('trainer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pokedex.trainer')),
>>>>>>> 940edef (Lab 6 completado)
            ],
        ),
    ]
